### PR TITLE
Combine airship bindings

### PR DESCRIPTION
**Pull request by rlepinski**
Moves the extension bindings into the airship bindings. Only way I could get the framework to actually copy into the app bundle.

### CODE REVIEW

**Comment by hcrowell** [comment]
🍊

**Comment by marc-scig** [comment]
let's get the android version numbers updated as well. I can push that

**Comment by rlepinski** [comment]
@marc-scig Android is versioned using the shared assembly. I believe we are good to go.

**Comment by marc-scig** [comment]
Oh right.

**Pull request closed without merging**
